import assert from 'node:assert/strict';
import { createServer, type Server } from 'node:http';
import { after, before, describe, it } from 'node:test';
import { loadConfig } from '../src/config.js';
import {
  SyncApiError,
  SyncClient,
  describeUploadError,
  isRetriableUploadError,
} from '../src/syncClient.js';

/**
 * These run against a real local HTTP server rather than a mocked fetch.
 *
 * The failure they exist for was invisible to a mock: undici 8's `request()`
 * accepted a FormData body, never serialised it, and the request hung until
 * the server gave up. Only something that actually reads the socket can tell
 * a well-formed multipart body from a body that was never sent.
 */

interface Capture {
  url: string;
  method: string;
  contentType: string;
  authorization: string;
  body: Buffer;
}

/** A stand-in for the PHP sync API, with scripted responses per request. */
class FakeSyncApi {
  readonly received: Capture[] = [];
  /** Statuses to answer with, in order. `null` destroys the connection. */
  script: (number | null)[] = [];
  private server!: Server;
  port = 0;

  async start(): Promise<void> {
    // A short requestTimeout is deliberate. If the client ever stops
    // serialising the body — which is precisely the bug these tests exist for
    // — the server would otherwise sit waiting and the suite would hang in CI
    // instead of failing. With this, a body that never arrives becomes a fast
    // 408 and a legible assertion failure.
    this.server = createServer({ requestTimeout: 3000 }, (req, res) => {
      const chunks: Buffer[] = [];
      req.on('data', (c: Buffer) => chunks.push(c));
      req.on('end', () => {
        this.received.push({
          url: req.url ?? '',
          method: req.method ?? '',
          contentType: req.headers['content-type'] ?? '',
          authorization: req.headers.authorization ?? '',
          body: Buffer.concat(chunks),
        });

        const next = this.script.length > 0 ? this.script.shift() : 200;

        if (next === null) {
          // A transport-level failure: the connection dies mid-response.
          req.socket.destroy();
          return;
        }

        const status = next ?? 200;
        res.writeHead(status, { 'content-type': 'application/json' });
        res.end(status < 400 ? '{"ok":true}' : '{"error":"nope"}');
      });
    });

    await new Promise<void>((resolve) => this.server.listen(0, '127.0.0.1', resolve));
    const address = this.server.address();
    this.port = typeof address === 'object' && address !== null ? address.port : 0;
  }

  async stop(): Promise<void> {
    await new Promise<void>((resolve) => this.server.close(() => resolve()));
  }

  reset(): void {
    this.received.length = 0;
    this.script = [];
  }
}

const api = new FakeSyncApi();
let client: SyncClient;

const SYNC_ID = 'a'.repeat(32);
const IMAGE = Buffer.from('RIFF    WEBPVP8 pretend-image-bytes');

before(async () => {
  await api.start();
  process.env.SITE_URL = `http://127.0.0.1:${api.port}`;
  process.env.MINNE_SYNC_API_KEY = 'test-key-0123456789';
  // Short: a hung request should fail the test quickly rather than stall it.
  process.env.REQUEST_TIMEOUT_MS = '4000';
  client = new SyncClient(loadConfig([]));
});

after(async () => {
  await client.close();
  await api.stop();
});

describe('sendImage multipart', () => {
  it('sends a body the server can actually read', async () => {
    api.reset();
    await client.sendImage(SYNC_ID, '12345', '00-thumb.webp', IMAGE);

    assert.equal(api.received.length, 1, 'the request must reach the server');
    const sent = api.received[0]!;

    assert.equal(sent.method, 'POST');
    assert.match(sent.url, /image\.php$/);

    // The boundary has to be present, and generated by the client.
    assert.match(sent.contentType, /^multipart\/form-data; boundary=/);
    const boundary = /boundary=(.+)$/.exec(sent.contentType)?.[1];
    assert.ok(boundary !== undefined && boundary.length > 10, 'a boundary must be set');

    const text = sent.body.toString('latin1');
    assert.ok(text.includes(`--${boundary}`), 'the body must use the declared boundary');

    for (const field of ['syncId', 'productId', 'filename', 'file']) {
      assert.ok(text.includes(`name="${field}"`), `missing field: ${field}`);
    }
    assert.ok(text.includes('filename="00-thumb.webp"'), 'the file part needs a filename');
    assert.ok(text.includes('image/webp'), 'the file part must declare its type');

    // The bytes themselves have to survive the encoding.
    assert.ok(sent.body.includes(IMAGE), 'the image bytes must arrive intact');

    assert.equal(sent.authorization, 'Bearer test-key-0123456789');
  });

  it('lets fetch generate a fresh boundary each time', async () => {
    api.reset();
    await client.sendImage(SYNC_ID, '12345', '01-large.webp', IMAGE);
    await client.sendImage(SYNC_ID, '12345', '02-large.webp', IMAGE);

    assert.notEqual(
      api.received[0]!.contentType,
      api.received[1]!.contentType,
      'a hand-set Content-Type would repeat the same boundary',
    );
  });
});

describe('sendImage retry', () => {
  it('retries a transport failure and succeeds', async () => {
    api.reset();
    api.script = [null, 200]; // connection destroyed, then fine

    await client.sendImage(SYNC_ID, '12345', '00-thumb.webp', IMAGE);

    assert.equal(api.received.length, 2, 'it must have tried twice');
    assert.ok(api.received[1]!.body.includes(IMAGE), 'the retry must resend the image');
  });

  it('retries a 5xx and succeeds', async () => {
    api.reset();
    api.script = [503, 200];

    await client.sendImage(SYNC_ID, '12345', '00-thumb.webp', IMAGE);

    assert.equal(api.received.length, 2);
  });

  it('does not retry a 4xx', async () => {
    api.reset();
    api.script = [422, 200];

    await assert.rejects(
      () => client.sendImage(SYNC_ID, '12345', 'bad-name.webp', IMAGE),
      (error: unknown) => error instanceof SyncApiError && error.status === 422,
    );

    assert.equal(api.received.length, 1, 'a 4xx is an answer, not a glitch');
  });

  it('gives up after three attempts', async () => {
    api.reset();
    api.script = [500, 500, 500];

    await assert.rejects(
      () => client.sendImage(SYNC_ID, '12345', '00-thumb.webp', IMAGE),
      (error: unknown) => error instanceof SyncApiError && error.status === 500,
    );

    assert.equal(api.received.length, 3, 'three attempts, then stop');
  });
});

describe('retry classification', () => {
  it('treats 5xx as transient and 4xx as final', () => {
    assert.equal(isRetriableUploadError(new SyncApiError('x', 500, '')), true);
    assert.equal(isRetriableUploadError(new SyncApiError('x', 503, '')), true);
    assert.equal(isRetriableUploadError(new SyncApiError('x', 400, '')), false);
    assert.equal(isRetriableUploadError(new SyncApiError('x', 401, '')), false);
    assert.equal(isRetriableUploadError(new SyncApiError('x', 422, '')), false);
  });

  it('treats a transport error as transient', () => {
    const transport = new TypeError('fetch failed');
    (transport as { cause?: unknown }).cause = Object.assign(new Error('socket hang up'), {
      code: 'ECONNRESET',
    });
    assert.equal(isRetriableUploadError(transport), true);
  });

  it('describes a failure without leaking the response body', () => {
    assert.equal(describeUploadError(new SyncApiError('x', 500, 'SECRET-BODY')), 'HTTP 500');

    const transport = new TypeError('fetch failed');
    (transport as { cause?: unknown }).cause = Object.assign(new Error('reset'), {
      code: 'ECONNRESET',
    });
    assert.equal(describeUploadError(transport), 'TypeError: ECONNRESET');
  });
});

describe('start and commit', () => {
  it('does not retry start', async () => {
    api.reset();
    api.script = [500, 200];

    await assert.rejects(() => client.start());

    assert.equal(api.received.length, 1, 'a repeated start would orphan a session');
  });

  it('does not retry commit', async () => {
    api.reset();
    api.script = [500, 200];

    await assert.rejects(() =>
      client.commit(SYNC_ID, { imageSuccess: 1, imageFailure: 0, mainImageFailure: 0 }),
    );

    assert.equal(api.received.length, 1, 'a repeated commit could publish twice');
  });

  it('reports whether abort actually succeeded', async () => {
    api.reset();
    api.script = [200];
    assert.equal(await client.abort(SYNC_ID, 'done'), true);

    api.reset();
    api.script = [500];
    // Still resolves rather than throwing — a failed sync is already on its
    // way to reporting the real cause — but it says so.
    assert.equal(await client.abort(SYNC_ID, 'done'), false);
  });

  it('can be closed after start fails, so a failed run leaks nothing', async () => {
    api.reset();
    api.script = [500];

    const doomed = new SyncClient(loadConfig([]));
    await assert.rejects(() => doomed.start());
    // The dispatcher is per-client, so this is what stops a failed start from
    // holding sockets open and delaying the process exit.
    await doomed.close();
  });

  it('sends JSON, not multipart, for the non-image calls', async () => {
    api.reset();
    api.script = [200];

    await client.start();

    assert.match(api.received[0]!.contentType, /^application\/json/);
  });
});
